# Generated by Django 4.2.9 on 2026-10-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=30, unique=True, verbose_name='批次号')),
                ('title', models.CharField(max_length=100, verbose_name='批次名称')),
                ('risk_levels', models.JSONField(blank=True, default=list, verbose_name='风险等级筛选')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('status', models.CharField(choices=[('open', '进行中'), ('concluded', '已结论')], default='open', max_length=20, verbose_name='状态')),
                ('conclusion', models.JSONField(blank=True, null=True, verbose_name='批次结论')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='结论形成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '盘点批次',
                'verbose_name_plural': '盘点批次',
                'db_table': 'iv_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='盘点数量')),
                ('result', models.CharField(choices=[('normal', '账实相符'), ('abnormal', '账实异常')], max_length=20, verbose_name='盘点结果')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '盘点记录',
                'verbose_name_plural': '盘点记录',
                'db_table': 'iv_record',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(max_length=40, unique=True, verbose_name='任务号')),
                ('status', models.CharField(choices=[('pending', '待领取'), ('claimed', '进行中'), ('done', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '盘点任务',
                'verbose_name_plural': '盘点任务',
                'db_table': 'iv_task',
                'ordering': ['task_no'],
            },
        ),
        migrations.CreateModel(
            name='StorageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='区域名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='区域编码')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=10, verbose_name='风险等级')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='区域说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '保管区',
                'verbose_name_plural': '保管区',
                'db_table': 'iv_storage_area',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='账面数量')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='盘点数量')),
                ('status', models.CharField(choices=[('pending', '待盘点'), ('counted', '已盘点'), ('abnormal', '异常待复核'), ('reviewed', '已复核'), ('removed', '已移出')], default='pending', max_length=20, verbose_name='状态')),
                ('removed_reason', models.CharField(blank=True, max_length=100, verbose_name='移出原因')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='盘点时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_items', to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='warehouse.goods', verbose_name='货物')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorytask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '任务明细',
                'verbose_name_plural': '任务明细',
                'db_table': 'iv_task_item',
                'ordering': ['id'],
                'unique_together': {('task', 'goods')},
            },
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to='inventory.storagearea', verbose_name='保管区'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_tasks', to=settings.AUTH_USER_MODEL, verbose_name='盘点员'),
        ),
        migrations.AddField(
            model_name='inventorytask',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inventory.inventorybatch', verbose_name='所属批次'),
        ),
        migrations.CreateModel(
            name='InventorySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=64, verbose_name='请求标识')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='提交结果摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='inventory.inventorytask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '分段提交单',
                'verbose_name_plural': '分段提交单',
                'db_table': 'iv_submission',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'request_id')},
            },
        ),
        migrations.CreateModel(
            name='InventoryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('confirmed', '确认差异'), ('recount', '退回重盘')], default='pending', max_length=20, verbose_name='状态')),
                ('final_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='核定数量')),
                ('review_note', models.CharField(blank=True, max_length=500, verbose_name='复核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.inventorytaskitem', verbose_name='任务明细')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inventory.inventoryrecord', verbose_name='异常记录')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reviews', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '异常复核单',
                'verbose_name_plural': '异常复核单',
                'db_table': 'iv_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.inventorytaskitem', verbose_name='任务明细'),
        ),
        migrations.AddField(
            model_name='inventoryrecord',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.inventorysubmission', verbose_name='所属提交单'),
        ),
        migrations.CreateModel(
            name='GoodsLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '锁定中'), ('released', '已释放')], default='active', max_length=20, verbose_name='状态')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='锁定时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('release_reason', models.CharField(blank=True, max_length=50, verbose_name='释放原因')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locks', to='warehouse.goods', verbose_name='货物')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='inventory.inventorytask', verbose_name='锁定任务')),
            ],
            options={
                'verbose_name': '物资盘点锁',
                'verbose_name_plural': '物资盘点锁',
                'db_table': 'iv_goods_lock',
                'ordering': ['-locked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='goodslock',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('goods',), name='uniq_active_goods_lock'),
        ),
    ]
