# Generated by Django 4.2.9 on 2026-10-03 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StocktakeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='批次名称')),
                ('locations', models.JSONField(default=list, verbose_name='盘点区域')),
                ('risk_levels', models.JSONField(default=list, verbose_name='风险等级')),
                ('deadline', models.DateTimeField(verbose_name='截止日期')),
                ('chunk_size', models.PositiveIntegerField(default=50, verbose_name='任务分块大小')),
                ('status', models.CharField(choices=[('draft', '待开始'), ('in_progress', '盘点中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='批次状态')),
                ('scope_version', models.PositiveIntegerField(default=1, verbose_name='范围版本')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='批次结论')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='结论形成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('concluded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concluded_batches', to=settings.AUTH_USER_MODEL, verbose_name='结论确认人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建主管')),
            ],
            options={
                'verbose_name': '盘点批次',
                'verbose_name_plural': '盘点批次',
                'db_table': 'iv_stocktake_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=10, verbose_name='盘点结果')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实盘数量')),
                ('abnormal_type', models.CharField(blank=True, choices=[('quantity', '数量不符'), ('status', '状态异常'), ('missing', '物资缺失'), ('other', '其他异常')], default='', max_length=20, verbose_name='异常类型')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('counted_at', models.DateTimeField(auto_now=True, verbose_name='最近盘点时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次提交时间')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='提交版本')),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_items', to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_items', to='warehouse.goods', verbose_name='物资')),
            ],
            options={
                'verbose_name': '盘点条目',
                'verbose_name_plural': '盘点条目',
                'db_table': 'iv_stocktake_item',
            },
        ),
        migrations.CreateModel(
            name='StocktakeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=30, verbose_name='任务编号')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='盘点区域')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='low', max_length=10, verbose_name='风险等级')),
                ('scope_version', models.PositiveIntegerField(default=1, verbose_name='所属范围版本')),
                ('is_supplement', models.BooleanField(default=False, verbose_name='是否范围增补任务')),
                ('status', models.CharField(choices=[('pending', '待领取'), ('in_progress', '盘点中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='任务状态')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='最近领取时间')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='最近释放时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('claim_count', models.PositiveIntegerField(default=0, verbose_name='累计领取次数')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='应盘数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_tasks', to=settings.AUTH_USER_MODEL, verbose_name='盘点员')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='inventory.stocktakebatch', verbose_name='盘点批次')),
            ],
            options={
                'verbose_name': '盘点任务',
                'verbose_name_plural': '盘点任务',
                'db_table': 'iv_stocktake_task',
                'ordering': ['batch_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='TaskGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, verbose_name='是否被进行中任务锁定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_locks', to='warehouse.goods', verbose_name='物资')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_goods', to='inventory.stocktaketask', verbose_name='盘点任务')),
            ],
            options={
                'verbose_name': '任务物资范围',
                'verbose_name_plural': '任务物资范围',
                'db_table': 'iv_task_goods',
            },
        ),
        migrations.CreateModel(
            name='StocktakeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('resolved', '已复核')], default='pending', max_length=20, verbose_name='复核状态')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='复核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='inventory.stocktakeitem', verbose_name='盘点条目')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktake_reviews', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '异常复核',
                'verbose_name_plural': '异常复核',
                'db_table': 'iv_stocktake_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktaketask', verbose_name='盘点任务'),
        ),
        migrations.AddConstraint(
            model_name='taskgoods',
            constraint=models.UniqueConstraint(condition=models.Q(('is_locked', True)), fields=('goods',), name='iv_task_goods_active_lock'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeitem',
            unique_together={('task', 'goods')},
        ),
    ]
